### ISSUE TITLE
eff_mo是什么东西&膜拜摁键不可用

### ISSUE THREAD

**Issue by wangdemao** [qz-cqy/sto-rui_er-orz#1]
RT

**Comment by qz-cqy** [comment]
> RT

eff_mo 是你点击一次按钮等小的膜拜次数，例如 eff_mo = 2，你点击一次增加两次膜拜。

膜拜按键已经在本地（Chrome+Firefox）测试，没有任何问题，请检查自己浏览器是否支持 localStorage。

**Comment by wangdemao** [comment]
eff_mo 应该初始化为 1 吧，要不然点一下会加 0 ，也就是没变

**Comment by wangdemao** [comment]
我早改了~~开挂了~~

**Comment by BenBen123-lg** [comment]
emm
