### ISSUE TITLE
Chinese Can't See!

### ISSUE THREAD

**Issue by BenBen123-lg** [qz-cqy/sto-rui_er-orz#2]
_~~VERY-STUPID rui_er!!~~(bushi_
中文乱码了呢，棕名神犇RUI_ER！！

**Comment by qz-cqy** [comment]
> _~VERY-STUPID rui_er!!~(bushi_
> 中文乱码了呢，棕名神犇RUI_ER！！

您好，中文没有乱码，是您的浏览器问题。

**Comment by BenBen123-lg** [comment]
emm

**Comment by BenBen123-lg** [comment]
离线版的~~Stupid rui_eer!!!!~~(bushi)

**Comment by BenBen123-lg** [comment]
@qz-cqy

**Comment by qz-cqy** [comment]
所以您想说啥

**Comment by BenBen123-lg** [comment]
[img]http://chuantu.xyz/t6/740/1597210400x1700340450.png[/img]

**Comment by BenBen123-lg** [comment]
修复!!!!!

**Comment by BenBen123-lg** [comment]
http://chuantu.xyz/t6/740/1597210400x1700340450.png

**Comment by BenBen123-lg** [comment]
能修复吗?

**Comment by qz-cqy** [comment]
不修复，以后也不会修复。本地和其他人均没有问题，是你自己浏览器的问题。请更换 Chrome 或火狐。

**Comment by BenBen123-lg** [comment]
emmmmm

**Comment by BenBen123-lg** [comment]
用ISO或者UTF-8不就好了吗

**Comment by BenBen123-lg** [comment]
@qz-cqy

**Comment by qz-cqy** [comment]
如果您坚持要修复一个根本不存在的错误的话，可以利用你 fork 的仓库进行修改，然后 pull request。

**Comment by Zsong2009** [comment]
emmm BenBen123-lg 您是猴吗？

**Comment by BenBen123-lg** [comment]
我怎么就是猴子了?

**Comment by qz-cqy** [comment]
To @BenBen123-lg : 

> **互相尊重。** 粗鲁是正常对话的天敌。 保持礼貌和专业，不要发表被理性的人视为冒犯、侮辱或仇恨的言论。 不要骚扰或打击任何人。 在所有互动中应互相尊重和体谅。——[《GitHub 社区指导方针》](https://docs.github.com/cn/github/site-policy/github-community-guidelines)

**Comment by BenBen123-lg** [comment]
好尴尬

**Comment by Zsong2009** [comment]
emmm，rui_er在lg上发了个链接

**Comment by BenBen123-lg** [comment]
我看看去，

**Comment by BenBen123-lg** [comment]
emm，Closed

**Comment by Ebeo-Yvnjiang** [comment]
2333

**Comment by qz-cqy** [comment]
> 2333

原来 close 了然后还可以回复是吗qaq

**Comment by BenBen123-lg** [comment]
呵呵

**Comment by UserUnknownX** [comment]
@qz-cqy 要lock才能停止回复，或者开强制冷静模式（所有人禁止回复1天），也可以禁止任意用户发布或回复issue

**Comment by BenBen123-lg** [comment]
> @qz-cqy 要lock才能停止回复，或者开强制冷静模式（所有人禁止回复1天），也可以禁止任意用户发布或回复issue

怎么能说出来呢，吼吼hi hi(开始学猴子叫)

**Comment by william-song-shy** [comment]
谁0202年还给你支持IE啊

**Comment by qz-cqy** [comment]
> 谁0202年还给你支持IE啊

正解

**Comment by tim1103** [comment]
> > 谁0202年还给你支持IE啊
> 
> 正解

正解

**Comment by UserUnknownX** [comment]
> > 谁0202年还给你支持IE啊
> 
> 正解

这人还用IE。。。怕不是整天登银行（（（wu

**Comment by qz-cqy** [comment]
看他就是没事找事。这东西谁都会修，我不修，因为一看你那语气，看你那态度，就不想修。

**Comment by qz-cqy** [comment]
再来一次小心被 block

**Comment by BenBen123-lg** [comment]
我错了...

**Comment by BenBen123-lg** [comment]
~~我才不会告诉你我是NiTuBenBen~~开玩笑ing

**Comment by BenBen123-lg** [comment]
猴子奸笑着走开了

**Comment by BenBen123-lg** [comment]
~~(跳楼去了~~
