### ISSUE TITLE
BUG 反馈

### ISSUE THREAD

**Issue by oier-jyb666** [qz-cqy/sto-rui_er-orz#4]
F12，打开 Console 输入：

### 自动膜拜

```
while(1)
    add();
```

稍等后刷新网页即可

**Comment by oier-jyb666** [comment]
话说 `add()` 也可以换成其他的

**Comment by oier-jyb666** [comment]
@qz-cqy

**Comment by qz-cqy** [comment]
> F12，打开 Console 输入：
> 
> ### 自动膜拜
> ```
> while(1)
>     add();
> ```
> 
> 稍等后刷新网页即可

这不是 bug，add() 是我的膜拜函数，不自动膜拜才怪。换成别的你录个视频给我，我才不信能行。

**Comment by BenBen123-lg** [comment]
good




| |
陆昱名
18510335982
Lu_Yu_Ming@163.com
欢迎聊天
|

签名由 网易邮箱大师 定制

在2020年08月14日 15:33，rui_er 写道：

F12，打开 Console 输入：

自动膜拜
while(1)

    add();



稍等后刷新网页即可

这不是 bug，add() 是我的膜拜函数，不自动膜拜才怪。换成别的你录个视频给我，我才不信能行。
